### ISSUE TITLE
Sobre borrador de Codigo de Conducta

### ISSUE THREAD

**Issue by nelruk** [PythonParaguay/docs#2]
En uno de los lineamientos, refiere lo siguiente:
_Comentarios curiosos, insultantes / despectivos y ataques personales o **políticos**._ (Los énfasis son míos)

¿Se podría contar con ejemplos o contextualizar mejor que es o a que se refiere con ataques políticos?

**Comment by melizeche** [comment]
@nelruk Se te ocurre algún ejemplo? eso lo saque del CoC del kernel de linux, creo que podriamos eliminarlo si no es claro o no se aplica tanto

**Comment by melizeche** [comment]
Se eliminó eso, más adelante si es necesario se puede volver a revisar, gracias por la sugerencia!
